[theme]
primaryColor = "#4F8EF7"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 200

[general]
email = "prachi_ss@ch.iitr.ac.in"

[client]
showSidebarNavigation = false

[layout]
wide = true